# Generated by Django 2.2.4 on 2019-08-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190819_0939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
